name: Deploy Azure Name App

on: 
    push:
        branches:
        - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v3
            - name: Setup node.js version 
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: cd ./newApp && npm install
            - name: Deploy to Azure
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'azure-teste'
                publish-profile: '${{secrets.AZURE_PUBLISH_PROFILE}}'
                package: ./NovaAplicacao


